baseURL = 'https://andrewhuang.vercel.app/'
languageCode = 'en-us'
title = "andrew huang"
theme = 'hugo-theme-hello-friend-ng'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
homeSubtitle = "current projects: <a href='https://andrewhuang.vercel.app/categories/zeromouse/'> zeromouse</a> and <a href='https://andrewhuang.vercel.app/categories/sumobot/'>sumobot</a>. <br> <br>"

  [[params.social]]
    name = "email"
    url  = "mailto:az42hu@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/destabilized"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "about"
    title      = "about"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "posts"
    title      = "posts"
    url        = "posts/"

  [[menu.main]]
    identifier = "projects"
    name       = "projects"
    url        = "projects/"
    title      = "projects"
